version: '3.2'

networks:
  backend:
  home_frontend:
    external: true

services:

  server:
    image: ffaerber/monsterborg-controller-server:latest
    environment:
      DEBUG: socket.io*
    networks:
      - backend
    deploy:
      labels:
        - "traefik.backend=socketio"
        - "traefik.frontend.rule=Host:socketio.ffaerber.com"
        - "traefik.port=3000"
      placement:
        constraints:
          - node.hostname == pi2
