version: '3.2'

networks:
  home_backend:
    external: true

services:

  server:
    image: ffaerber/monsterborg-controller-server:latest
    networks:
      - home_backend
    deploy:
      labels:
        - "traefik.backend=socketio"
        - "traefik.frontend.rule=Host:socketio.ffaerber.com"
        - "traefik.port=3000"
      placement:
        constraints:
          - node.hostname == pi2

  rtmp:
    image: ffaerber/monsterborg-controller-rtmp:latest
    networks:
      - home_backend
    deploy:
      labels:
        - "traefik.backend=rtmp"
        - "traefik.frontend.rule=Host:rtmp.ffaerber.com"
        - "traefik.port=8000"
      placement:
        constraints:
          - node.hostname == pi2
